# Generated by Django 5.0 on 2023-12-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_availability_options_alter_brands_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='Customers',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='Employees',
        ),
        migrations.AlterModelTable(
            name='permissions',
            table='Permissions',
        ),
    ]
